### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by sowenjub**
Just typos I spotted as I read the code.

### CODE REVIEW

**Review by ggruen — CHANGES_REQUESTED** [review]
Well, that's embarrassing. :)

What you fixed to "accounted" is supposed to be "announced" though (that is, the phrase should be "announced or not announced") - can you change that (don't think I can edit directly in a pull request)? Then I can approve this pull request.

Thanks!

Grant

**Comment by sowenjub** [comment]
Haha. I'll be honest, I tossed a coin. I thought announced made more sense but accounted was just one letter away.

**Review by ggruen — APPROVED** [review]
Ok, I (hopefully) figured out how to edit the file in the pull request, so approving.

**Comment by sowenjub** [comment]
By the way, thanks for this package @ggruen 🙏

**Comment by ggruen** [comment]
You're welcome - glad you like it.

**Pull request merged**
